### ISSUE TITLE
Template V-Solution Zabbix

### ISSUE THREAD

**Issue by JuarezPrates** [remontti/Zabbix-Templates#1]
Espero que **ninguém** precise, **mas** aqui está:
[rr-vsol.txt](https://github.com/remontti/Zabbix-Templates/files/7091094/rr-vsol.txt)

**Comment by Keijipena** [comment]
Hola, ¿cómo estás? ¿Puedo utilizar zabbix para manipular OLTS VSOL?

**Comment by JuarezPrates** [comment]
Hola. Puedes usar estos OIDs como base para descubrir los otros, ya que la
MIB es difícil de encontrar y no tengo más el archivo. Es posible, pero no
llegué a desarrollar hasta ese punto.

Em sáb., 31 de ago. de 2024 às 23:45, Keiji Peña ***@***.***>
escreveu:

**Comment by vortexti** [comment]
Credits to Rudimar remontti  www.remontti.com.br for template..

link to updates of template:   https://github.com/remontti/Zabbix-Templates
